USE id2086086_songs;

SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS songs;
SET FOREIGN_KEY_CHECKS = 1;
CREATE TABLE IF NOT EXISTS songs (
	songKey INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(50),
    artist VARCHAR(50),
    setlist VARCHAR(50),
    songDate DATETIME
);