USE id2086086_songs;

SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS songs;
SET FOREIGN_KEY_CHECKS = 1;
CREATE TABLE IF NOT EXISTS songs (
    title VARCHAR(50),
    artist VARCHAR(50),
    songDate DATETIME,
    PRIMARY KEY (title, artist)
);